vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|23 Mar 2006 12:34:53 -0000
vti_extenderversion:SR|4.0.2.7802
vti_filesize:IR|21740
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=big5 HTTP-EQUIV=Pragma no-cache
vti_backlinkinfo:VX|yfyemp/functiona.asp yfyemp/admin/admin01.asp
vti_cacheddtm:TX|17 Sep 2006 16:19:20 -0000
vti_cachedlinkinfo:VX|Q|../Include/style.css Q|../Include/style2.css A|ADMIN01.ASP S|../picture/LOGONEW.gif H|vbscript:chgpage(1) S|../picture/BTN01.gif H|vbscript:chgpage(2) S|../picture/BTNA1.GIF H|vbscript:chgpage(3) S|../picture/BTNB1.GIF H|vbscript:chgpage(4) S|../picture/BTNC1.gif H|vbscript:chgpage(5) S|../picture/BTND1.gif H|vbscript:chgpage(6) S|../picture/BTNe1.gif H|vbscript:chgpage(7) S|../picture/BTNf1.gif H|vbscript:chgpage(8) S|../picture/BTNG1.gif S|../picture/banner03.gif S|../picture/icon06.GIF H|admin01.asp H|newuser.asp H|user.edit.asp H|vbscript:chgpage(9)
vti_cachedsvcrellinks:VX|FQUS|YFYEMP/Include/style.css FQUS|YFYEMP/Include/style2.css FAUS|YFYEMP/ADMIN/ADMIN01.ASP NSUS|YFYEMP/picture/LOGONEW.gif NHUS|vbscript:chgpage(1) NSUS|YFYEMP/picture/BTN01.gif NHUS|vbscript:chgpage(2) NSUS|YFYEMP/picture/BTNA1.GIF NHUS|vbscript:chgpage(3) NSUS|YFYEMP/picture/BTNB1.GIF NHUS|vbscript:chgpage(4) NSUS|YFYEMP/picture/BTNC1.gif NHUS|vbscript:chgpage(5) NSUS|YFYEMP/picture/BTND1.gif NHUS|vbscript:chgpage(6) NSUS|YFYEMP/picture/BTNe1.gif NHUS|vbscript:chgpage(7) NSUS|YFYEMP/picture/BTNf1.gif NHUS|vbscript:chgpage(8) NSUS|YFYEMP/picture/BTNG1.gif NSUS|YFYEMP/picture/banner03.gif NSUS|YFYEMP/picture/icon06.GIF FHUS|YFYEMP/ADMIN/admin01.asp NHUS|YFYEMP/ADMIN/newuser.asp NHUS|YFYEMP/ADMIN/user.edit.asp NHUS|vbscript:chgpage(9)
vti_cachedtitle:SR|VYFYNET
vti_title:SR|VYFYNET
vti_cachedbodystyle:SR|<body leftmargin="0"  topmargin="0"  marginwidth="0" marginheight="0" onLoad="MM_preloadImages('../picture/BTN02.gif','../picture/BTNA2.GIF','../picture/BTNb2.gif','../picture/BTNC2.GIF','../picture/BTND2.gif','../picture/BTNe2.gif','../picture/BTNF2.gif','../picture/BTNG2.GIF')" onkeydown="enterto()" >
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
