vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|06 Jul 2004 09:56:16 -0000
vti_extenderversion:SR|4.0.2.7802
vti_cacheddtm:TX|06 Jul 2004 09:56:16 -0000
vti_filesize:IR|9805
vti_cachedlinkinfo:VX|Q|./../Include/style.css Q|../../Include/style2.css S|..\\\\..\\\\Picture\\\\bg9.gif A|<%=self%> A|<%=action%>
vti_cachedsvcrellinks:VX|FQUS|YFYEMP/Include/style.css FQUS|Include/style2.css NSUS|/YFYEMP/SYSPRO/..\\\\..\\\\Picture\\\\bg9.gif UAUS|<%=self%> UAUS|<%=action%>
vti_cachedbodystyle:SR|<body onload="sta()" background="..\\..\\Picture\\bg9.gif">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_backlinkinfo:VX|
