<%@LANGUAGE=VBSCRIPT CODEPAGE=65001%>
 
<HTML>
<HEAD>
 
<META HTTP-EQUIV="Content-Type" content="text/html; charset=utf-8">
<meta HTTP-EQUIV="Pragma" CONTENT="no-cache">
</HEAD>
  <frameset cols="100%,0" frameborder = "NO" framespacing=0>  
	<frame	SRC = "YFYEXRT.Fore.asp?pgid=<%=request("pgid")%>"  
			name="Main"  
			framespacing=0 
			frameborder=0 
			scrolling="auto" 
			noresize>
	<frame	SRC = "YFYEXRT.Back2.asp?pgid=<%=request("pgid")%>" 
			name = "Back"  
			framespacing=0 
			frameborder=0 
			scrolling="auto">
  </frameset>

</HTML>


