<!-- this page is make by Johnson Wang -->

<SCRIPT TYPE="text/javascript">

    if (navigator.userAgent.indexOf("MSIE") == -1 || navigator.appVersion.substring(0,1) < 4)
    
		{
			window.location.replace("../default.asp");
		}

	
</SCRIPT>

<SCRIPT TYPE="text/javascript">

	function clikker(a,b) {
		if (a.style.display =='') {
			a.style.display = 'none';
			b.src='picture/dot_y2.gif';
		}
		else {
 			a.style.display='';
			b.src='picture/dot_y3.gif';
		}
	}
	
</SCRIPT>
