vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|25 Sep 2006 09:15:58 -0000
vti_extenderversion:SR|4.0.2.7802
vti_filesize:IR|634
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=BIG5 HTTP-EQUIV=Pragma no-cache
vti_hasframeset:BR|true
vti_backlinkinfo:VX|yfyemp/functiona.asp
vti_cacheddtm:TX|25 Sep 2006 09:15:58 -0000
vti_cachedlinkinfo:VX|F|YFYEXRT.Fore.asp F|YFYEXRT.Back.asp
vti_cachedsvcrellinks:VX|FFUS|YFYEMP/employee/empbasic/YFYEXRT.Fore.asp FFUS|YFYEMP/employee/empbasic/YFYEXRT.Back.asp
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
