vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|25 Sep 2006 09:13:49 -0000
vti_extenderversion:SR|4.0.2.7802
vti_filesize:IR|798
vti_metatags:VR|HTTP-EQUIV=Pragma no-cache HTTP-EQUIV=refresh
vti_backlinkinfo:VX|yfyemp/employee/empbasic/yfyexrt.asp
vti_cacheddtm:TX|25 Sep 2006 09:13:49 -0000
vti_cachedlinkinfo:VX|
vti_cachedsvcrellinks:VX|
vti_cachedbodystyle:SR|<BODY>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
