vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|08 Sep 2007 19:08:30 -0000
vti_extenderversion:SR|4.0.2.7802
vti_cacheddtm:TX|08 Sep 2007 19:08:30 -0000
vti_filesize:IR|10354
vti_cachedlinkinfo:VX|Q|../Include/style.css Q|../Include/style2.css S|bg_blue.gif A|<%=SELF%>.Fore.asp S|../image/icon.gif
vti_cachedsvcrellinks:VX|FQUS|YFYEMP/Include/style.css FQUS|YFYEMP/Include/style2.css NSUS|YFYEMP/YEG/bg_blue.gif UAUS|<%=SELF%>.Fore.asp FSUS|YFYEMP/image/icon.gif
vti_cachedtitle:SR|稅別
vti_title:SR|稅別
vti_cachedbodystyle:SR|<body background="bg_blue.gif"  topmargin=5>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=UTF-8 HTTP-EQUIV=Pragma no-cache HTTP-EQUIV=refresh
vti_backlinkinfo:VX|
