/*
 * File: components/payroll/LuongT13Details.js
 * Mô tả: Component hiển thị chi tiết phiếu lương tháng 13.
 */
import React from 'react';

export default function LuongT13Details({ data, year }) {
    if (!data) return <p className="text-center text-gray-500 mt-4">Dữ liệu lương tháng 13 cho năm {year} chưa được cập nhật.</p>;
    
    const formatCurrency = (amount) => (typeof amount !== 'number' || isNaN(amount)) ? '0' : Math.round(amount).toLocaleString('vi-VN');
    const tongLuongTinhThuong = data.TongLuong - (data.ChuyenCan || 0);

    return (
        <div className="bg-slate-50 p-4 sm:p-6 lg:p-8 rounded-2xl max-w-4xl mx-auto font-sans">
            <header className="text-center mb-8"><h2 className="text-3xl font-bold text-gray-800">Phiếu Lương Thưởng Tháng 13</h2><p className="text-lg text-gray-500">Năm {year}</p></header>
            <div className="bg-white p-4 rounded-lg shadow-sm mb-6 flex justify-between items-center">
                <div><p className="text-lg font-bold text-indigo-700">{data.HoTen}</p><p className="text-sm text-gray-500">MSNV: {data.MSNV}</p></div>
                {data.ChucVu && <p className="text-sm text-gray-600 font-medium bg-gray-100 px-3 py-1 rounded-full">{data.ChucVu}</p>}
            </div>
            <div className="bg-gradient-to-r from-green-500 to-teal-500 text-white p-6 rounded-xl text-center mb-8 shadow-lg shadow-green-200"><p className="text-lg font-semibold uppercase tracking-wider opacity-80">Thực Lãnh</p><p className="text-5xl font-bold tracking-tight">{formatCurrency(data.ThucLanh)} <span className="text-3xl opacity-80">VNĐ</span></p></div>
            <div className="grid md:grid-cols-2 gap-6 mb-8">
                <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6"><div className="flex items-center mb-4"><div className="bg-green-100 text-green-600 p-2 rounded-full mr-4"><svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v.01" /></svg></div><h3 className="text-xl font-bold text-gray-700">Thu Nhập</h3></div><div className="space-y-3"><div className="flex justify-between items-center text-base"><span className="text-gray-600">Thưởng tháng 13</span><span className="font-semibold text-gray-800">{formatCurrency(data.TienThuongThang13)}</span></div><div className="flex justify-between items-center text-base"><span className="text-gray-600">Tiền phép năm</span><span className="font-semibold text-gray-800">{formatCurrency(data.TienPhepNam)}</span></div></div><div className="border-t my-4"></div><div className="flex justify-between items-center text-lg"><span className="font-bold text-gray-600">Tổng cộng</span><span className="font-bold text-green-600">{formatCurrency(data.TongCong)}</span></div></div>
                <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6"><div className="flex items-center mb-4"><div className="bg-red-100 text-red-600 p-2 rounded-full mr-4"><svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M18 12H6" /></svg></div><h3 className="text-xl font-bold text-gray-700">Khoản Trừ</h3></div><div className="space-y-3"><div className="flex justify-between items-center text-base"><span className="text-gray-600">Trừ khác (biên bản...)</span><span className="font-semibold text-gray-800">{formatCurrency(data.TienTruKhac)}</span></div></div><div className="border-t my-4"></div><div className="flex justify-between items-center text-lg"><span className="font-bold text-gray-600">Tổng trừ</span><span className="font-bold text-red-600">{formatCurrency(data.TienTruKhac)}</span></div></div>
            </div>
            <details className="bg-white rounded-lg shadow-sm border border-gray-200 p-4 group"><summary className="font-semibold text-gray-700 cursor-pointer list-none flex justify-between items-center">Xem chi tiết & các chỉ số tham chiếu<svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 transition-transform duration-300 group-open:rotate-180" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg></summary><div className="mt-4 pt-4 border-t grid grid-cols-2 md:grid-cols-3 gap-x-6 gap-y-3 text-sm"><div><p className="text-gray-500">Lương cơ bản</p><p className="font-semibold">{formatCurrency(data.LuongCoBan)}</p></div><div><p className="text-gray-500">Tổng lương (không chuyên cần)</p><p className="font-semibold">{formatCurrency(tongLuongTinhThuong)}</p></div><div><p className="text-gray-500">Hệ số thưởng</p><p className="font-semibold">{(data.HeSoThuong || 0).toFixed(2)}</p></div><div><p className="text-gray-500">Số ngày công</p><p className="font-semibold">{data.SoNgayCongThucTe}</p></div><div><p className="text-gray-500">Số tiếng phép còn lại</p><p className="font-semibold">{data.SoTiengPhepNamConLai}</p></div><div><p className="text-gray-500">Số ngày nghỉ không lương</p><p className="font-semibold">{data.SoNgayNghiKhongLuong}</p></div></div></details>
            <div className="mt-6 bg-gray-100 p-4 rounded-lg text-xs text-gray-600 space-y-1"><p className="font-bold text-gray-800">GHI CHÚ:</p><p><span className="font-semibold">* Tiền thưởng tháng 13</span> = Tổng lương(Không tính chuyên cần)/365* số ngày làm việc thực tế * hệ số thưởng</p><p><span className="font-semibold">* Tiền phép năm</span> = (Lương cơ bản + P/C chức vụ + P/C kỹ thuật + P/C Điện thoại + P/C Xăng xe + P/C Nhà ở+chuyên cần)/26/8*số tiếng phép năm còn lại</p><p><span className="font-semibold">* Hệ số</span> = Số ngày tính hệ số thưởng/30</p><p><span className="font-semibold">* Thực lãnh</span> = Tiền thưởng tháng 13 + Tiền phép năm - Tiền bị trừ khi lập biên bản - tiền khống công</p><p>(Ghi chú : 1 lần bị lập biên bản sẽ bị trừ tương ứng 5 ngày làm việc thực tế)</p></div>
        </div>
    );
}
