vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|29 Aug 2007 07:44:59 -0000
vti_extenderversion:SR|4.0.2.7802
vti_cacheddtm:TX|29 Aug 2007 07:44:59 -0000
vti_filesize:IR|10254
vti_cachedlinkinfo:VX|Q|../Include/style.css Q|../Include/style2.css A|ADMIN01.ASP
vti_cachedsvcrellinks:VX|FQUS|YFYEMP/Include/style.css FQUS|YFYEMP/Include/style2.css FAUS|YFYEMP/SYSPRO/ADMIN01.ASP
vti_cachedbodystyle:SR|<body leftmargin="0"  topmargin="0"  marginwidth="0" marginheight="0" onLoad="MM_preloadImages('../picture/BTN02.gif','../picture/BTNA2.GIF','../picture/BTNb2.gif','../picture/BTNC2.GIF','../picture/BTND2.gif','../picture/BTNe2.gif','../picture/BTNF2.gif','../picture/BTNG2.GIF')" onkeydown="enterto()" >
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=big5 HTTP-EQUIV=Pragma no-cache
vti_backlinkinfo:VX|yfyemp/syspro/admin01.asp
