vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|17 Mar 2008 03:31:31 -0000
vti_extenderversion:SR|4.0.2.7802
vti_cacheddtm:TX|17 Mar 2008 03:31:31 -0000
vti_filesize:IR|17198
vti_cachedlinkinfo:VX|Q|../Include/style.css Q|../Include/style2.css A|<%=self%>.upd.asp S|../image/icon.gif
vti_cachedsvcrellinks:VX|FQUS|YFYEMP/Include/style.css FQUS|YFYEMP/Include/style2.css UAUS|<%=self%>.upd.asp FSUS|YFYEMP/image/icon.gif
vti_cachedbodystyle:SR|<body  topmargin="0" leftmargin="0"  marginwidth="0" marginheight="0"  onkeydown="enterto()" onload="f()">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8 HTTP-EQUIV=Pragma no-cache HTTP-EQUIV=refresh
vti_backlinkinfo:VX|
