vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|09 Jun 2008 02:15:27 -0000
vti_extenderversion:SR|4.0.2.7802
vti_cacheddtm:TX|09 Jun 2008 02:15:27 -0000
vti_filesize:IR|692
vti_cachedlinkinfo:VX|F|<%=self%>.accdata.asp F|<%=self%>.back.asp
vti_cachedsvcrellinks:VX|UFUS|<%=self%>.accdata.asp UFUS|<%=self%>.back.asp
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8 HTTP-EQUIV=Pragma no-cache
vti_hasframeset:BR|true
vti_backlinkinfo:VX|
